<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
        <TargetFrameworks Condition="'$(ContinuousIntegrationBuild)' != 'true'">net10.0</TargetFrameworks>
        <TargetFrameworks Condition="'$(ContinuousIntegrationBuild)' == 'true'">netstandard2.1;net8.0;net10.0</TargetFrameworks>
        
        <!-- Path to BC dev tools may be overridden by /p:BcDevToolsDir= -->
        <BcDevToolsDir Condition="'$(BcDevToolsDir)'==''">../../Microsoft.Dynamics.BusinessCentral.Development.Tools</BcDevToolsDir>
    </PropertyGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="ALCops.Common.Test" />
        <EmbeddedResource Update="ALCops.CommonAnalyzers.resx">
            <LogicalName>ALCops.Common.CommonAnalyzers.resources</LogicalName>
            <Generator>MSBuild:Compile</Generator>
            <StronglyTypedLanguage>CSharp</StronglyTypedLanguage>
            <StronglyTypedNamespace>ALCops.Common</StronglyTypedNamespace>
            <StronglyTypedFileName>$(IntermediateOutputPath)ALCops.CommonAnalyzers.cs</StronglyTypedFileName>
            <StronglyTypedClassName>CommonAnalyzers</StronglyTypedClassName>
        </EmbeddedResource>
        <Compile Include="$(IntermediateOutputPath)ALCops.CommonAnalyzers.cs"
                 Condition="'$(DesignTimeBuild)' == 'true' and Exists('$(IntermediateOutputPath)ALCops.CommonAnalyzers.cs')"
                 Visible="false">
            <AutoGen>true</AutoGen>
            <DesignTime>true</DesignTime>
            <DependentUpon>ALCops.CommonAnalyzers.resx</DependentUpon>
        </Compile>
    </ItemGroup>
    <ItemGroup>
        <Reference Include="Microsoft.Dynamics.Nav.CodeAnalysis">
            <SpecificVersion>False</SpecificVersion>
            <HintPath>$(BcDevToolsDir)/$(TargetFramework)/Microsoft.Dynamics.Nav.CodeAnalysis.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Microsoft.Dynamics.Nav.Analyzers.Common">
            <SpecificVersion>False</SpecificVersion>
            <HintPath>$(BcDevToolsDir)/$(TargetFramework)/Microsoft.Dynamics.Nav.Analyzers.Common.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>

    <!-- Legacy support for netstandard2.1 -->
    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
        <PackageReference Include="System.Collections.Immutable" />
        <Reference Include="Newtonsoft.Json">
            <SpecificVersion>False</SpecificVersion>
            <HintPath>$(BcDevToolsDir)/$(TargetFramework)/Newtonsoft.Json.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>
</Project>
